name: Composer Command
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "project path where located composer.json (/composer/{project1})"
        required: true
        type: string
      command:
        description: "composer {command}"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, zip, pdo
          coverage: none

      - name: Install Composer dependencies
        run: composer self-update

      - name: Run
        run: |
          COMPOSER_PATH="$PWD/../../composer"
          PROJECT_NAME="${{ github.event.inputs.project_name }}"
          PROJECT_PATH="$COMPOSER_PATH/$PROJECT_NAME"
          ARCHIVE_PATH="$COMPOSER_PATH/$PROJECT_NAME.zip"

          mkdir -p $PROJECT_PATH

          cd $PROJECT_PATH
          composer ${{ github.event.inputs.command }}

          cd $COMPOSER_PATH
          zip -r "$ARCHIVE_PATH" "$PROJECT_PATH"

          cd ..
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$ARCHIVE_PATH"
          git commit -m $PROJECT_NAME
          git push
