name: Composer Command
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "project path where located composer.json (/composer/{project1})"
        required: true
        type: string
      command:
        description: "composer {command}"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, zip, pdo
          coverage: none

      - name: Install Composer dependencies
        run: composer self-update

      - name: Run
        run: |
          BASE_PATH="$PWD/../../composer"
          PROJECT_NAME="$BASE_PATH/${{ github.event.inputs.project_name }}"
          ARCHIVE_PATH="$BASE_PATH/${{ github.event.inputs.project_name }}.zip"
          PROJECT_DIR="$(dirname "$PROJECT_NAME")"

          mkdir -p $PROJECT_NAME

          cd $PROJECT_NAME

          composer ${{ github.event.inputs.command }}

          cd $PROJECT_DIR
          zip -r "$ARCHIVE_PATH" "$PROJECT_NAME"

          cd ..
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$ARCHIVE_PATH"
          git commit -m $ARCHIVE_PATH
          git push
